production:
  clients:
    default:
      database: temps
      hosts: ["<%= ENV['MONGODB_ADDRESS'] || 'mongodb'%>:27017"]
development:
  clients:
    default:
      database: temps
      hosts: ["<%= ENV['MONGODB_ADDRESS'] || 'mongodb'%>:27017"]
      
